language: php
php:
- '8.0'

notifications:
- email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "HostName test-deploy.knoskov.ru\n\tStrictHostKeyChecking no\n\t"User deploy >> ~/.ssh/config 
jobs:
  include:
    - stage: deploy
      if: env(TYPE) = deploy
      name: "Deploy"
      install:
        - composer self-update
        - composer install --no-interaction
      script: vendor/bin/phpunit
      deploy:
        skip_cleanup: true
        provider: script
        script: vendor/bin/dep deploy
        on:
          branch: master

    - stage: rollback
      if: env(TYPE) = rollback
      name: "Rollback"
      deploy:
        provider: script
        script: vendor/bin/dep rollback
        on:
          branch: master