language: php
php:
    - '8.0'
install:
    - composer self-update
    - composer install --no-interaction
script: 
    - vendor/bin/phpunit

before_deploy:
  - openssl aes-256-cbc -K $encrypted_<put_your_key_here>_key -iv $encrypted_<put_your_key_here>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "HostName test-deploy.knoskov.ru\n\tStrictHostKeyChecking no\n\t"User deploy >> ~/.ssh/config 

deploy:
  skip_cleanup: true
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: master

notifications: 
    - email: false