language: php
php:
    - '8.0'
install:
    - composer self-update
    - composer install --no-interaction
script: 
    - vendor/bin/phpunit

deploy: 
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master

notifications: 
    - email: false