language: php
php:
    - '7.4'
    - '8.0'
install:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - php artisan config:clear
script: 
    - vendor/bin/phpunit