language: php
php:
- '8.0'
install:
- composer self-update
- composer install --no-interaction
script:
- vendor/bin/phpunit
deploy:
  skip_cleanup: true
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: master
notifications:
- email: false
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "HostName test-deploy.knoskov.ru\n\tStrictHostKeyChecking no\n\t"User deploy >> ~/.ssh/config 